[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvisgrid"
dynamic = ["version"]
description = " Grid and visualize observations of radio interferometers."
readme = "README.md"
authors = [{ name = "Kevin Schmitz, Tom Groß, Anno Knierim" }]
maintainers = [
  { name = "Kevin Schmitz", email = "kevin2.schmitz@tu-dortmund.de" },
  { name = "Tom Groß", email = "tom.gross@tu-dortmund.de" },
  { name = "Anno Knierim", email = "anno.knierim@tu-dortmund.de" },
]
license = { text = "MIT" }
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Development Status :: 4 - Beta",
]

requires-python = ">=3.10"

dependencies = [
  "astropy<=6.1.0",
  "click",
  "h5py",
  "ipython",
  "jupyter",
  "matplotlib",
  "numpy",
  "pandas",
  "scipy",
  "toml",
  "torch",
  "tqdm",
  "casatools",
  "pyvisgen@git+https://github.com/radionets-project/pyvisgen#egg=main",
]

[project.optional-dependencies]

tests = ["h5py", "pytest >= 7.0", "pytest-cov", "tomli"]

dev = ["pre-commit"]

[project.urls]
repository = "https://github.com/radionets-project/pyvisgrid"

[tool.setuptools_scm]
write_to = "pyvisgrid/_version.py"

[tool.setuptools.packages.find]
where = ["."]
